name: myenv_R
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - pandas
  - numpy
  - scipy
  - anndata=0.11.3
  - pip
  - pip:
    - matplotlib
    - seaborn
    - scikit-learn

name: otherenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scipy